# Generated by Django 3.1.7 on 2021-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_num', models.AutoField(primary_key=True, serialize=False)),
                ('child_id', models.CharField(max_length=32)),
                ('child_area', models.CharField(max_length=32)),
                ('child_schoolname', models.CharField(db_column='child_schoolName', max_length=100)),
                ('child_name', models.CharField(max_length=32)),
                ('child_sex', models.CharField(max_length=10)),
                ('child_birth', models.CharField(max_length=10)),
                ('child_height', models.FloatField(blank=True, null=True)),
                ('child_weight', models.FloatField(blank=True, null=True)),
                ('child_profile', models.TextField(blank=True, null=True)),
                ('child_bmi', models.FloatField(blank=True, db_column='child_BMI', null=True)),
            ],
            options={
                'db_table': 'child',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_num', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(max_length=32)),
                ('parent_email', models.CharField(max_length=100, unique=True)),
                ('parent_pwd', models.CharField(max_length=32)),
                ('parent_name', models.CharField(max_length=32)),
                ('parent_tel', models.CharField(max_length=11, unique=True)),
                ('parent_birth', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Parent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_num', models.AutoField(db_column='recipe_num', primary_key=True, serialize=False)),
                ('recipe_id', models.CharField(db_column='recipe_id', max_length=32)),
                ('recipe_name', models.CharField(db_column='recipe_name', max_length=100)),
                ('recipe_method', models.CharField(db_column='recipe_method', max_length=50)),
                ('recipe_kind', models.CharField(db_column='recipe_kind', max_length=50)),
                ('recipe_difficulty', models.FloatField(blank=True, null=True)),
                ('recipe_rating', models.FloatField(blank=True, null=True)),
                ('recipe_ingredient', models.CharField(db_column='recipe_ingredient', max_length=600)),
                ('recipe_kcal', models.CharField(db_column='recipe_kcal', max_length=16)),
                ('recipe_carbohydrate', models.CharField(db_column='recipe_carbohydrate', max_length=16)),
                ('recipe_protein', models.CharField(db_column='recipe_protein', max_length=16)),
                ('recipe_fat', models.CharField(db_column='recipe_fat', max_length=16)),
                ('recipe_natrium', models.CharField(db_column='recipe_natrium', max_length=16)),
                ('recipe_thumbnail', models.CharField(db_column='recipe_thumbnail', max_length=150)),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeRating_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reciperating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_num', models.AutoField(db_column='recommnedation_num', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recommendation',
                'managed': False,
            },
        ),
    ]
