# Generated by Django 3.1 on 2021-03-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_num', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(max_length=32)),
                ('parent_email', models.CharField(max_length=100, unique=True)),
                ('parent_pwd', models.CharField(max_length=32)),
                ('parent_name', models.CharField(max_length=32)),
                ('parent_tel', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'db_table': 'Parent',
                'managed': False,
            },
        ),
    ]
