# Generated by Django 3.1.7 on 2021-03-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_num', models.AutoField(primary_key=True, serialize=False)),
                ('child_id', models.CharField(max_length=32)),
                ('child_area', models.CharField(max_length=32)),
                ('child_schoolname', models.CharField(db_column='child_schoolName', max_length=100)),
                ('child_name', models.CharField(max_length=32)),
                ('child_sex', models.CharField(max_length=10)),
                ('child_birth', models.CharField(max_length=10)),
                ('child_height', models.FloatField(blank=True, null=True)),
                ('child_weight', models.FloatField(blank=True, null=True)),
                ('child_profile', models.TextField(blank=True, null=True)),
                ('child_bmi', models.FloatField(blank=True, db_column='child_BMI', null=True)),
            ],
            options={
                'db_table': 'child',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schoolschedule',
            fields=[
                ('schoolschedule_num', models.AutoField(db_column='schoolSchedule_num', primary_key=True, serialize=False)),
                ('schoolschedule_id', models.CharField(db_column='schoolSchedule_id', max_length=32)),
                ('schoolschedule_date', models.CharField(blank=True, db_column='schoolSchedule_date', max_length=30)),
                ('schoolschedule_content', models.CharField(blank=True, db_column='schoolSchedule_content', max_length=100)),
            ],
            options={
                'db_table': 'schoolschedule',
                'managed': False,
            },
        ),
    ]
