# Generated by Django 3.1.7 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_child_schoolschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolfeeding',
            fields=[
                ('schoolfeeding_num', models.AutoField(db_column='schoolFeeding_num', primary_key=True, serialize=False)),
                ('schoolfeeding_id', models.CharField(db_column='schoolFeeding_id', max_length=32)),
                ('schoolfeeding_date', models.CharField(blank=True, db_column='schoolFeeding_date', max_length=30, null=True)),
                ('schoolfeeding_type', models.CharField(blank=True, db_column='schoolFeeding_type', max_length=30, null=True)),
                ('schoolfeeding_kcal', models.CharField(blank=True, db_column='schoolFeeding_kcal', max_length=16, null=True)),
                ('schoolfeeding_carbohydrate', models.CharField(blank=True, db_column='schoolFeeding_carbohydrate', max_length=16, null=True)),
                ('schoolfeeding_protein', models.CharField(blank=True, db_column='schoolFeeding_protein', max_length=16, null=True)),
                ('schoolfeeding_fat', models.CharField(blank=True, db_column='schoolFeeding_fat', max_length=16, null=True)),
                ('schoolfeeding_vitamina', models.CharField(blank=True, db_column='schoolFeeding_vitaminA', max_length=16, null=True)),
                ('schoolfeeding_thiamine', models.CharField(blank=True, db_column='schoolFeeding_thiamine', max_length=16, null=True)),
                ('schoolfeeding_riboflavin', models.CharField(blank=True, db_column='schoolFeeding_riboflavin', max_length=16, null=True)),
                ('schoolfeeding_vitaminc', models.CharField(blank=True, db_column='schoolFeeding_vitaminC', max_length=16, null=True)),
                ('schoolfeeding_calcium', models.CharField(blank=True, db_column='schoolFeeding_calcium', max_length=16, null=True)),
                ('schoolfeeding_iron', models.CharField(blank=True, db_column='schoolFeeding_iron', max_length=16, null=True)),
            ],
            options={
                'db_table': 'schoolfeeding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schoolfeedingdetail',
            fields=[
                ('schoolfeedingdetail_num', models.AutoField(db_column='schoolFeedingDetail_num', primary_key=True, serialize=False)),
                ('schoolfeedingdetail_id', models.CharField(db_column='schoolFeedingDetail_id', max_length=32)),
                ('schoolfeedingdetail_foodno1', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo1', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno1allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo1Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno2', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo2', max_length=100, null=True)),
                ('schoolfeedingdetail_foodnoallergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNoAllergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno3', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo3', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno3allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo3Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno4', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo4', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno4allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo4Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno5', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo5', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno5allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo5Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno6', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo6', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno6allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo6Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno7', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo7', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno7allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo7Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno8', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo8', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno8allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo8Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno9', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo9', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno9allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo9Allergy', max_length=50, null=True)),
                ('schoolfeedingdetail_foodno10', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo10', max_length=100, null=True)),
                ('schoolfeedingdetail_foodno10allergy', models.CharField(blank=True, db_column='schoolFeedingDetail_foodNo10Allergy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'schoolfeedingdetail',
                'managed': False,
            },
        ),
    ]
