# Generated by Django 3.1.7 on 2021-09-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_schoolfeeding_schoolfeedingdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parent',
            table='parent',
        ),
    ]
