-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 13:39:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema formychild
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formychild
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formychild` DEFAULT CHARACTER SET utf8 ;
USE `formychild` ;

-- -----------------------------------------------------
-- Table `formychild`.`Parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Parent` (
  `parent_num` INT NOT NULL,
  `parent_id` VARCHAR(32) NOT NULL,
  `parent_email` VARCHAR(100) NOT NULL,
  `parent_pwd` VARCHAR(32) NOT NULL,
  `parent_name` VARCHAR(32) NOT NULL,
  `parent_tel` CHAR(11) NOT NULL,
  `parent_birth` CHAR(10) NOT NULL,
  PRIMARY KEY (`parent_num`, `parent_id`),
  INDEX `parent_id` (`parent_id` ASC) VISIBLE,
  UNIQUE INDEX `parent_email_UNIQUE` (`parent_email` ASC) VISIBLE,
  UNIQUE INDEX `parent_tel_UNIQUE` (`parent_tel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Child` (
  `child_num` INT NOT NULL AUTO_INCREMENT,
  `child_id` VARCHAR(32) NOT NULL,
  `child_parentId` VARCHAR(32) NOT NULL,
  `child_area` VARCHAR(32) NOT NULL,
  `child_schoolName` VARCHAR(100) NOT NULL,
  `child_name` VARCHAR(32) NOT NULL,
  `child_age` INT NULL,
  `child_height` INT NULL,
  `child_weight` INT NULL,
  `child_profile` BLOB NULL,
  `child_BMI` INT NULL,
  PRIMARY KEY (`child_num`, `child_id`),
  INDEX `fk_child_parent_idx` (`child_parentId` ASC) VISIBLE,
  INDEX `child_id` (`child_id` ASC) VISIBLE,
  CONSTRAINT `fk_child_parent`
    FOREIGN KEY (`child_parentId`)
    REFERENCES `formychild`.`Parent` (`parent_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Allergy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Allergy` (
  `allergy_num` INT NOT NULL AUTO_INCREMENT,
  `allergy_id` VARCHAR(32) NOT NULL,
  `allergy_childId` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`allergy_num`, `allergy_id`),
  INDEX `fk_allergy_child1_idx` (`allergy_childId` ASC) VISIBLE,
  INDEX `allergy_id` (`allergy_id` ASC) VISIBLE,
  CONSTRAINT `fk_allergy_child1`
    FOREIGN KEY (`allergy_childId`)
    REFERENCES `formychild`.`Child` (`child_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`AllergyDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`AllergyDetail` (
  `allergyDetail_num` INT NOT NULL AUTO_INCREMENT,
  `allergyDetail_id` VARCHAR(32) NOT NULL,
  `allergyDetail_allergyId` VARCHAR(32) NOT NULL,
  `allergyDetail_allergyName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`allergyDetail_num`, `allergyDetail_id`),
  INDEX `fk_allergyDetail_allergy1_idx` (`allergyDetail_allergyId` ASC) VISIBLE,
  INDEX `allergyDetail_id` (`allergyDetail_id` ASC) VISIBLE,
  CONSTRAINT `fk_allergyDetail_allergy1`
    FOREIGN KEY (`allergyDetail_allergyId`)
    REFERENCES `formychild`.`Allergy` (`allergy_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Refrigerator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Refrigerator` (
  `refrigerator_num` INT NOT NULL AUTO_INCREMENT,
  `refrigerator_id` VARCHAR(32) NOT NULL,
  `refrigerator_parentsId` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`refrigerator_num`, `refrigerator_id`),
  INDEX `fk_refrigerator_parent1_idx` (`refrigerator_parentsId` ASC) VISIBLE,
  INDEX `refrigerator_id` (`refrigerator_id` ASC) VISIBLE,
  CONSTRAINT `fk_refrigerator_parent1`
    FOREIGN KEY (`refrigerator_parentsId`)
    REFERENCES `formychild`.`Parent` (`parent_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`RefrigeratorDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`RefrigeratorDetail` (
  `refrigeratorDetail_num` INT NOT NULL AUTO_INCREMENT,
  `refrigeratorDetail_id` VARCHAR(32) NOT NULL,
  `refrigeratorDetail_refrigeratorId` VARCHAR(32) NOT NULL,
  `refrigeratorDetail_ingredientName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`refrigeratorDetail_num`, `refrigeratorDetail_id`),
  INDEX `fk_refrigeratorDetail_refrigerator1_idx` (`refrigeratorDetail_refrigeratorId` ASC) VISIBLE,
  INDEX `refrigeratorDetail_id` (`refrigeratorDetail_id` ASC) VISIBLE,
  CONSTRAINT `fk_refrigeratorDetail_refrigerator1`
    FOREIGN KEY (`refrigeratorDetail_refrigeratorId`)
    REFERENCES `formychild`.`Refrigerator` (`refrigerator_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`RecipeIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`RecipeIngredient` (
  `recipeIngredient_num` INT NOT NULL AUTO_INCREMENT,
  `recipeIngredient_id` VARCHAR(32) NOT NULL,
  `recipeIngredient_ingredient` VARCHAR(100) NOT NULL,
  `recipeIngredient_kcal` VARCHAR(16) NOT NULL,
  `recipeIngredient_carbohydrate` VARCHAR(16) NULL,
  `recipeIngredient_protein` VARCHAR(16) NULL,
  `recipeIngredient_fat` VARCHAR(16) NULL,
  `recipeIngredient_natrium` VARCHAR(16) NULL,
  PRIMARY KEY (`recipeIngredient_num`, `recipeIngredient_id`),
  INDEX `recipeIngredient_id` (`recipeIngredient_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`RecipeProcess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`RecipeProcess` (
  `recipeProcess_num` INT NOT NULL AUTO_INCREMENT,
  `recipeProcess_id` VARCHAR(32) NOT NULL,
  `recipeProcess_no1` VARCHAR(300) NOT NULL,
  `recipeProcess_image1` BLOB NULL,
  `recipeProcess_no2` VARCHAR(300) NULL,
  `recipeProcess_image2` BLOB NULL,
  `recipeProcess_no3` VARCHAR(300) NULL,
  `recipeProcess_image3` BLOB NULL,
  `recipeProcess_no4` VARCHAR(300) NULL,
  `recipeProcess_image4` BLOB NULL,
  `recipeProcess_no5` VARCHAR(300) NULL,
  `recipeProcess_image5` BLOB NULL,
  `recipeProcess_no6` VARCHAR(300) NULL,
  `recipeProcess_image6` BLOB NULL,
  `recipeProcess_no7` VARCHAR(300) NULL,
  `recipeProcess_image7` BLOB NULL,
  `recipeProcess_no8` VARCHAR(300) NULL,
  `recipeProcess_image8` BLOB NULL,
  `recipeProcess_no9` VARCHAR(300) NULL,
  `recipeProcess_image9` BLOB NULL,
  `recipeProcess_no10` VARCHAR(300) NULL,
  `recipeProcess_image10` BLOB NULL,
  `recipeProcess_no11` VARCHAR(300) NULL,
  `recipeProcess_image11` BLOB NULL,
  `recipeProcess_no12` VARCHAR(300) NULL,
  `recipeProcess_image12` BLOB NULL,
  `recipeProcess_no13` VARCHAR(300) NULL,
  `recipeProcess_image13` BLOB NULL,
  `recipeProcess_no14` VARCHAR(300) NULL,
  `recipeProcess_image14` BLOB NULL,
  `recipeProcess_no15` VARCHAR(300) NULL,
  `recipeProcess_image15` BLOB NULL,
  `recipeProcess_no16` VARCHAR(300) NULL,
  `recipeProcess_image16` BLOB NULL,
  `recipeProcess_no17` VARCHAR(300) NULL,
  `recipeProcess_image17` BLOB NULL,
  `recipeProcess_no18` VARCHAR(300) NULL,
  `recipeProcess_image18` BLOB NULL,
  `recipeProcess_no19` VARCHAR(300) NULL,
  `recipeProcess_image19` BLOB NULL,
  `recipeProcess_no20` VARCHAR(300) NULL,
  `recipeProcess_image20` BLOB NULL,
  PRIMARY KEY (`recipeProcess_num`, `recipeProcess_id`),
  INDEX `recipeProcess_id` (`recipeProcess_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`RecipeInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`RecipeInfo` (
  `recipeInfo_num` INT NOT NULL AUTO_INCREMENT,
  `recipeInfo_id` VARCHAR(32) NOT NULL,
  `recipeInfo_name` VARCHAR(100) NOT NULL,
  `recipeInfo_method` VARCHAR(50) NOT NULL,
  `recipeInfo_kind` VARCHAR(50) NOT NULL,
  `recipeInfo_difficultly` INT NOT NULL DEFAULT 0,
  `recipeInfo_scope` INT NOT NULL DEFAULT 0,
  `recipeInfo_thumbnail` BLOB NULL,
  PRIMARY KEY (`recipeInfo_num`, `recipeInfo_id`),
  INDEX `recipeInfo_id` (`recipeInfo_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Recipe` (
  `recipe_num` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` VARCHAR(32) NOT NULL,
  `recipe_recipeInfoId` VARCHAR(32) NOT NULL,
  `recipe_recipeProcessId` VARCHAR(32) NOT NULL,
  `recipe_recipeNutritionInfoId` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`recipe_num`, `recipe_id`),
  INDEX `recipe_id` (`recipe_id` ASC) VISIBLE,
  INDEX `fk_Recipe_RecipeNutritionInfo1_idx` (`recipe_recipeNutritionInfoId` ASC) VISIBLE,
  INDEX `fk_Recipe_RecipeProcess1_idx` (`recipe_recipeProcessId` ASC) VISIBLE,
  INDEX `fk_Recipe_RecipeInfo1_idx` (`recipe_recipeInfoId` ASC) VISIBLE,
  CONSTRAINT `fk_Recipe_RecipeNutritionInfo1`
    FOREIGN KEY (`recipe_recipeNutritionInfoId`)
    REFERENCES `formychild`.`RecipeIngredient` (`recipeIngredient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recipe_RecipeProcess1`
    FOREIGN KEY (`recipe_recipeProcessId`)
    REFERENCES `formychild`.`RecipeProcess` (`recipeProcess_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Recipe_RecipeInfo1`
    FOREIGN KEY (`recipe_recipeInfoId`)
    REFERENCES `formychild`.`RecipeInfo` (`recipeInfo_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`FoodRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`FoodRecord` (
  `foodRecord_num` INT NOT NULL AUTO_INCREMENT,
  `foodRecord_id` VARCHAR(32) NOT NULL,
  `foodRecord_childId` VARCHAR(32) NOT NULL,
  `foodRecord_recipeId` VARCHAR(32) NOT NULL,
  `foodRecord_date` DATETIME NOT NULL DEFAULT NOW(),
  `foodRecord_media` BLOB NULL,
  PRIMARY KEY (`foodRecord_num`, `foodRecord_id`),
  INDEX `foodRecord_id` (`foodRecord_id` ASC) VISIBLE,
  INDEX `fk_foodRecord_child1_idx` (`foodRecord_childId` ASC) VISIBLE,
  INDEX `fk_FoodRecord_Recipe1_idx` (`foodRecord_recipeId` ASC) VISIBLE,
  CONSTRAINT `fk_foodRecord_child1`
    FOREIGN KEY (`foodRecord_childId`)
    REFERENCES `formychild`.`Child` (`child_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FoodRecord_Recipe1`
    FOREIGN KEY (`foodRecord_recipeId`)
    REFERENCES `formychild`.`Recipe` (`recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Scrap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Scrap` (
  `scrap_num` INT NOT NULL AUTO_INCREMENT,
  `scrap_id` VARCHAR(32) NOT NULL,
  `scrap_childId` VARCHAR(32) NOT NULL,
  `scrap_recipeId` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`scrap_num`, `scrap_id`),
  INDEX `fk_scrap_child1_idx` (`scrap_childId` ASC) VISIBLE,
  INDEX `scrap_id` (`scrap_id` ASC) VISIBLE,
  INDEX `fk_scrap_recipe1_idx` (`scrap_recipeId` ASC) VISIBLE,
  CONSTRAINT `fk_scrap_child1`
    FOREIGN KEY (`scrap_childId`)
    REFERENCES `formychild`.`Child` (`child_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_scrap_recipe1`
    FOREIGN KEY (`scrap_recipeId`)
    REFERENCES `formychild`.`Recipe` (`recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`RecipeScope`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`RecipeScope` (
  `recipeScope_num` INT NOT NULL AUTO_INCREMENT,
  `recipeScope_id` VARCHAR(32) NOT NULL,
  `recipeScope_recipeId` VARCHAR(32) NOT NULL,
  `recipeScope_parentId` VARCHAR(32) NOT NULL,
  `recipeScope_scope` INT NOT NULL,
  PRIMARY KEY (`recipeScope_num`, `recipeScope_id`),
  INDEX `recipeScope_id` (`recipeScope_id` ASC) VISIBLE,
  INDEX `fk_recipeScope_parent1_idx` (`recipeScope_recipeId` ASC) VISIBLE,
  INDEX `fk_recipeScope_recipe1_idx` (`recipeScope_parentId` ASC) VISIBLE,
  CONSTRAINT `fk_recipeScope_parent1`
    FOREIGN KEY (`recipeScope_recipeId`)
    REFERENCES `formychild`.`Parent` (`parent_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipeScope_recipe1`
    FOREIGN KEY (`recipeScope_parentId`)
    REFERENCES `formychild`.`Recipe` (`recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`RecipeDifficulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`RecipeDifficulty` (
  `recipeDifficulty_num` INT NOT NULL AUTO_INCREMENT,
  `recipeDifficulty_id` VARCHAR(32) NOT NULL,
  `recipeDifficulty_parentId` VARCHAR(32) NOT NULL,
  `recipeDifficulty_recipeId` VARCHAR(32) NOT NULL,
  `recipeDifficulty_difficulty` INT NOT NULL,
  PRIMARY KEY (`recipeDifficulty_num`, `recipeDifficulty_id`),
  INDEX `recipeDifficulty_id` (`recipeDifficulty_id` ASC) VISIBLE,
  INDEX `fk_recipeDifficulty_parent1_idx` (`recipeDifficulty_parentId` ASC) VISIBLE,
  INDEX `fk_recipeDifficulty_recipe1_idx` (`recipeDifficulty_recipeId` ASC) VISIBLE,
  CONSTRAINT `fk_recipeDifficulty_parent1`
    FOREIGN KEY (`recipeDifficulty_parentId`)
    REFERENCES `formychild`.`Parent` (`parent_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipeDifficulty_recipe1`
    FOREIGN KEY (`recipeDifficulty_recipeId`)
    REFERENCES `formychild`.`Recipe` (`recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`FoodCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`FoodCategory` (
  `foodCategory_num` INT NOT NULL AUTO_INCREMENT,
  `foodCategory_id` VARCHAR(32) NOT NULL,
  `foodCategory_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`foodCategory_num`, `foodCategory_id`),
  INDEX `foodCategory_id` (`foodCategory_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`FoodIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`FoodIngredient` (
  `foodIngredient_num` INT NOT NULL AUTO_INCREMENT,
  `foodIngredient_id` VARCHAR(32) NOT NULL,
  `foodIngredient_foodCategoryId` VARCHAR(32) NOT NULL,
  `foodIngredient_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`foodIngredient_num`, `foodIngredient_id`),
  INDEX `foodIngredient_id` (`foodIngredient_id` ASC) INVISIBLE,
  INDEX `fk_foodIngredient_foodCategory1_idx` (`foodIngredient_foodCategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_foodIngredient_foodCategory1`
    FOREIGN KEY (`foodIngredient_foodCategoryId`)
    REFERENCES `formychild`.`FoodCategory` (`foodCategory_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Preference` (
  `preference_num` INT NOT NULL AUTO_INCREMENT,
  `preference_id` VARCHAR(32) NOT NULL,
  `preference_foodIngredientId` VARCHAR(32) NOT NULL,
  `preference_childId` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`preference_num`, `preference_id`),
  INDEX `preference_id` (`preference_id` ASC) VISIBLE,
  INDEX `fk_preference_foodIngredient1_idx` (`preference_foodIngredientId` ASC) VISIBLE,
  INDEX `fk_preference_child1_idx` (`preference_childId` ASC) VISIBLE,
  CONSTRAINT `fk_preference_foodIngredient1`
    FOREIGN KEY (`preference_foodIngredientId`)
    REFERENCES `formychild`.`FoodIngredient` (`foodIngredient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_preference_child`
    FOREIGN KEY (`preference_childId`)
    REFERENCES `formychild`.`Child` (`child_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Tip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Tip` (
  `tip_num` INT NOT NULL AUTO_INCREMENT,
  `tip_id` VARCHAR(32) NOT NULL,
  `tip_title` VARCHAR(50) NOT NULL,
  `tip_content` VARCHAR(500) NOT NULL,
  `tip_media` BLOB NOT NULL,
  PRIMARY KEY (`tip_num`, `tip_id`),
  INDEX `tip_id` (`tip_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Message` (
  `message_num` INT NOT NULL AUTO_INCREMENT,
  `message_id` VARCHAR(32) NOT NULL,
  `message_senderId` VARCHAR(32) NOT NULL,
  `message_receiverId` VARCHAR(32) NOT NULL,
  `message_content` VARCHAR(100) NOT NULL,
  `message_flag` INT NOT NULL DEFAULT 1,
  `Message_` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`message_num`, `message_id`),
  INDEX `message_id` (`message_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`Todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`Todo` (
  `todo_num` INT NOT NULL AUTO_INCREMENT,
  `todo_id` VARCHAR(32) NOT NULL,
  `todo_parentId` VARCHAR(32) NOT NULL,
  `todo_childId` VARCHAR(32) NOT NULL,
  `todo_content` VARCHAR(100) NULL,
  `Todo_check` INT NULL,
  `todo_date` CHAR(10) NULL,
  PRIMARY KEY (`todo_num`, `todo_id`),
  INDEX `fk_Todo_Parent1_idx` (`todo_parentId` ASC) VISIBLE,
  INDEX `fk_Todo_Child1_idx` (`todo_childId` ASC) VISIBLE,
  INDEX `todo_id` (`todo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Todo_Parent1`
    FOREIGN KEY (`todo_parentId`)
    REFERENCES `formychild`.`Parent` (`parent_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Todo_Child1`
    FOREIGN KEY (`todo_childId`)
    REFERENCES `formychild`.`Child` (`child_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formychild`.`AllergyInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formychild`.`AllergyInfo` (
  `allergyInfo_num` INT NOT NULL AUTO_INCREMENT,
  `allergyInfo_id` VARCHAR(32) NOT NULL,
  `allergyInfo_category` INT NOT NULL,
  `allergyInfo_name` VARCHAR(50) CHARACTER SET 'armscii8' NOT NULL,
  PRIMARY KEY (`allergyInfo_num`, `allergyInfo_id`),
  INDEX `alleryInfo_id` (`allergyInfo_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
